### ISSUE TITLE
Slack/Discord + Flare Integration

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare-plugins#2]
**Is your feature request related to a problem? Please describe.**
I don't know if it is possible, but it would be very cool if you could connect a Flare bot to Slack so that you can do / commands in slack such as /hours which could show you how many hours you have or any other things that might work.

**Describe the solution you'd like**
A pilot being able to easily view certain things from Flare directly in Slack.

**Describe alternatives you've considered**
The pilot opening Flare and looking for themselves.

**Additional context**
Once again, this would be cool but it's not a top priority!

**Comment by Velocity23** [comment]
Could also be used for Discord through the Discord Slack Webhook format. See https://discord.com/developers/docs/resources/webhook#execute-slackcompatible-webhook.

**Comment by samdog2727** [comment]
@Velocity23 , anyway to do the above and/or adding the pilot's callsign when Slack gets a notification when a pilot files a flight?
