### ISSUE TITLE
Application Questions

### ISSUE THREAD

**Issue by samdog2727** [va-net/flare-plugins#5]
**Is your feature request related to a problem? Please describe.**
Not really. This is just a cool idea for a feature.

**Describe the solution you'd like**
VAs are able to add both long answer and multiple choice questions (somewhat like a google form) that pilots can fill out. The multiple choice questions would be very cool if they could be predetermined correct and wrong answers. This information could be collected into an "Applicant's Summary" showing their email, Grade and violations-landings, percentage of correct multiple choice answers. Using this could help fill in variables in email sent to applicant.

**Describe alternatives you've considered**
Using a different platform for an entrance exam.

**Additional context**
I can provide Thai Group Virtual's entrance exam to show what kind of things would be awesome to see.

**Comment by velocity23** [comment]
This will become a core feature in the future
